flight planner step 2 done!
ElvisBekis/flight-planner pull request #1
Opened 2022-04-25 11:54 UTC by ElvisBekis

2022-04-29 12:03 UTC, NilsKula requested changes

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRepository.java
> +    Set<Airport> airports = new HashSet<>();
private un šo vajadzētu atdalīt kā `airportRepository`

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/airport/Airport.java
> +        return airport.trim()
šī daļa tev atkārtojas 3x, notiekti var tad izvilkt uz palīgmetodi
`.trim().toUpperCase().contains(search.trim().toUpperCase()) `

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/airport/Airport.java
> +    public boolean doesAirportContainsPhrase(String search) {
nedaudz bikls nosaukums liekas, maybe something like `matchesSearchCriteria`

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRequest.java
> +public class FlightRequest {
pārak generic? `AddFlightRequest`

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRequest.java
> +@Validated
is this needed? :thinking:

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/SearchFlightReturn.java
> +    Set<Flight> items;
private

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightAdminController.java
> +        Flight flight = flightRequest.toDomain(flightService.setFlightId());
controlierī neveic kaut kadas datu manipulācijas
šeit šīs 3 rindiņas varētu aizvietot ar vienu
`return flightService.addFlight(flightRequest)`

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/Flight.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
šo jau var klases līmenī

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/Flight.java
> +                && departureTime.format(formatter).equals(String.format(request.getDepartureDate(), formatter));
tev jau paterns paliek taspats, LocalDateTime var vienkārši pārvērst uz LocalDate un requestā ņemt kā LocalDate ne String

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRepository.java
> +    public Set<Airport> getAirports() {
un šis tad varēs būt vienkārši airport repository un sanāks daudz īsāk

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRepository.java
> +    public boolean checkForDouble(Flight flight) {
just `exists` ? :thinking:

2022-04-29 12:03 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/SearchFlightRequest.java
> +@Validated
arī te

2022-05-03 17:03 UTC, ElvisBekis commented on src/main/java/io/codelex/flightplanner/flight/Flight.java
> +                && departureTime.format(formatter).equals(String.format(request.getDepartureDate(), formatter));
Visu citu izlaboju, bet šis man īsti nesanāk, kā es varu pieņemt kā LocalDate, ja request nāk kā Strings!

2022-05-03 20:54 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/airport/AirportRepository.java
> +    Set<Airport> airports = new HashSet<>();
visu variable pirms konstruktor un private

2022-05-03 20:54 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/airport/AirportRepository.java
> +    FlightRepository flightRepository;
private final

2022-05-03 20:54 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/FlightRepository.java
>      Set<Flight> flights = new HashSet<>();
arī private

2022-05-03 20:54 UTC, NilsKula commented on src/main/java/io/codelex/flightplanner/flight/Flight.java
> +                && departureTime.format(formatter).equals(String.format(request.getDepartureDate(), formatter));
paprovē `SearchFlightRequest` klasē pielikt ` @JsonFormat(pattern = "yyyy-MM-dd")`

2022-05-03 20:57 UTC, NilsKula requested changes
requests mapi pārsauc uz `api` 
overall labi 👍

2022-05-04 19:52 UTC, NilsKula approved these changes

2022-05-05 08:33 UTC, merged